version: "3"

services:
  cdl-server:
    build: 
      context: .
      dockerfile: cdl-server.Dockerfile
    ports:
      - "8000:8000"

  cdl-master:
    depends_on:
      - cdl-server
    build: 
      context: .
      dockerfile: cdl-master.Dockerfile
    volumes:
      - ./locustfile.py:/locustfile.py
      - ./shape.py:/shape.py
      - ./results:/results
    ports:
      - "8089:8089"
    command: -f /locustfile.py,/shape.py --master -H http://cdl-server:8000 -L INFO --run-time 60
    # command: -f /mnt/locust/locustfile.py --master --csv=loadresults/load -H http://cdl-server:8000 -L INFO

  cdl-worker:
    depends_on:
      - cdl-master
    build: 
      context: .
      dockerfile: cdl-worker.Dockerfile
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host cdl-master